### PR TITLE
Enable obfuscation for ccp queries

### PR DESCRIPTION
**Pull request by TKussel**
Enable statistical obfuscation for CCP query results. Chosen Parameters:

* Epsilon = 0.28
* Sensitivity Patients/Specimen/Diagnosis/Procedures/Medication Statements= 1/20/3/1.7/2.1
* Don't obfuscate real zeros
* Display 10 for 0 < count < 10
* Round to the next 10s

Required for merging:

- [x] Handle DKTK MeasureReport in Focus
- [x] Test in Mannheim
- [x] Go-ahead from CCP office

### CODE REVIEW

**Comment by enola-dkfz** [comment]
Focus is not ready because MeasureReport in DKTK differs from the one in BBMRI.

**Comment by TKussel** [comment]
> Focus is not ready because MeasureReport in DKTK differs from the one in BBMRI.

Thanks, I have added this precondition to the PR description

**Review by enola-dkfz — APPROVED** [review]
Best to merge after Focus develop is merged into main

**Review by patrickskowronekdkfz — CHANGES_REQUESTED** [review]
Currently the ccp focus is also used by the exliquid dashboard, which does not want obfuscation. My proposal would be to add another focus for this project.

**Comment by TKussel** [comment]
What about this: we include the obfuscation state as a variable, that you can override in the exliquid setup?

**Comment by enola-dkfz** [comment]
> What about this: we include the obfuscation state as a variable, that you can override in the exliquid setup?

In which application would that be done? If it's a parameter sent by Lens, that's a security issue. 

Because project/query language is already intended to be sent in metadata of the query, inserted by the Very Large Telescope, we could obfuscate, or not, depending on the project.

**Comment by enola-dkfz** [comment]
now the obfuscation is turnoffable in Focus based on the project
it is automatically turned off for the exliquid project
the beam tasks coming from exliquid dashboard should have this metadata
"metadata":{"project":"exliquid"}

**Review by patrickskowronekdkfz — APPROVED** [review]

**Pull request merged**
